
#pragma once

/**
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 * Generated by command 'canSotCli genCode -f motorControllerCanProtocol.def.yaml -o ../firmware/src/canSot/protocol_generated/ --client '.
 * For the client.
 */

#include "objectTree/OTNodeValueTypeDefs.h"
#include "objectTree/OTDeclares.h"
#include "objectTree/ProtocolDef.h"
#include "remoteCalls/RemoteCalls.h"

namespace MotorControllerCanProtocolNamespace {

enum class MOTOR_OPERATION_MODE {
	CONFIGURATION_PROCESS = 3,
	CONTROL_PD = 2,
	DO_NOTHING = 0,
};
enum class REQUEST_MOTOR_OPERATION_MODE {
	CONTROL_PD = 2,
	DO_NOTING = 0,
};
enum class REQUEST_MOTOR_OPERATION_MODE_ERROR {
	MOTOR_NOT_CONFIGURED = 0,
};
enum class MOTOR_ENABLED {
	DISABLED = 1,
	ENABLED = 0,
};
enum class MOTOR_CONFIG_DIRECTION {
	INVERSE = 1,
	NORMAL = 0,
};
enum class BOOL {
	FALSE = 0,
	TRUE = 1,
};




struct StartMotorInitSequenceArgDataCallable: RemoteCallDataReadable {
	TYPE_UINT16 throttle;


  StartMotorInitSequenceArgDataCallable(TYPE_UINT16 throttle): throttle(throttle) {}
  StartMotorInitSequenceArgDataCallable() = default;

  const uint8_t getRequiredDataSizeBytes() final {
    return sizeof(TYPE_UINT16);
  }

  /**
   * Read value from data of a can frame.
   * This will overwrite the current value of the node.
   * This will also set the wasChangedEvent to true.
   */
  inline void _readFromData(const uint8_t *data) final {
 		readFromDataUINT16(data[0], throttle);

  }
};

struct StartMotorInitSequenceReturnDataCallable: RemoteCallDataWritable {
	TYPE_F32 motorAlignmentOffset;
	TYPE_UINT8 electricalRotationsPerRevolution;
	MOTOR_CONFIG_DIRECTION motorDirection;


  StartMotorInitSequenceReturnDataCallable(TYPE_F32 motorAlignmentOffset,TYPE_UINT8 electricalRotationsPerRevolution,MOTOR_CONFIG_DIRECTION motorDirection): motorAlignmentOffset(motorAlignmentOffset), electricalRotationsPerRevolution(electricalRotationsPerRevolution), motorDirection(motorDirection) {}
  StartMotorInitSequenceReturnDataCallable() = default;

  const uint8_t getRequiredDataSizeBytes() final {
    return sizeof(TYPE_F32) + sizeof(TYPE_UINT8) + sizeof(uint8_t);
  }

  /**
   * Write value to data of a can frame.
   */
  inline void _writeToData(uint8_t *data) final {
 		writeToDataF32(data[0], motorAlignmentOffset);
		writeToDataUINT8(data[sizeof(TYPE_F32)], electricalRotationsPerRevolution);
		writeToDataENUM(data[sizeof(TYPE_F32) + sizeof(TYPE_UINT8)], motorDirection);

  }
};


struct SetMotorParametersArgDataCallable: RemoteCallDataReadable {
	TYPE_INT16 encoderElectricalOffset;
	TYPE_UINT8 electricalRotationsPerRevolution;
	MOTOR_CONFIG_DIRECTION motorDirection;


  SetMotorParametersArgDataCallable(TYPE_INT16 encoderElectricalOffset,TYPE_UINT8 electricalRotationsPerRevolution,MOTOR_CONFIG_DIRECTION motorDirection): encoderElectricalOffset(encoderElectricalOffset), electricalRotationsPerRevolution(electricalRotationsPerRevolution), motorDirection(motorDirection) {}
  SetMotorParametersArgDataCallable() = default;

  const uint8_t getRequiredDataSizeBytes() final {
    return sizeof(TYPE_INT16) + sizeof(TYPE_UINT8) + sizeof(uint8_t);
  }

  /**
   * Read value from data of a can frame.
   * This will overwrite the current value of the node.
   * This will also set the wasChangedEvent to true.
   */
  inline void _readFromData(const uint8_t *data) final {
 		readFromDataINT16(data[0], encoderElectricalOffset);
		readFromDataUINT8(data[sizeof(TYPE_INT16)], electricalRotationsPerRevolution);
		readFromDataENUM(data[sizeof(TYPE_INT16) + sizeof(TYPE_UINT8)], motorDirection);

  }
};


struct ChangeMotorOperationModeArgDataCallable: RemoteCallDataReadable {
	REQUEST_MOTOR_OPERATION_MODE requestedOperationMode;


  ChangeMotorOperationModeArgDataCallable(REQUEST_MOTOR_OPERATION_MODE requestedOperationMode): requestedOperationMode(requestedOperationMode) {}
  ChangeMotorOperationModeArgDataCallable() = default;

  const uint8_t getRequiredDataSizeBytes() final {
    return sizeof(uint8_t);
  }

  /**
   * Read value from data of a can frame.
   * This will overwrite the current value of the node.
   * This will also set the wasChangedEvent to true.
   */
  inline void _readFromData(const uint8_t *data) final {
 		readFromDataENUM(data[0], requestedOperationMode);

  }
};



}
