
#pragma once

/**
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 * Generated by command 'canSotCli genCode -f motorControllerCanProtocol.def.yaml -o src/can_master_lib/protocol_generated/ --master '.
 */

#include <objectTree/OTNodeValueTypeDefs.h>
#include <objectTree/OTDeclares.h>
#include <objectTree/ProtocolDef.h>
#include "MotorControllerCanProtocol_Structs.hpp"

namespace MotorControllerCanProtocolNamespace {


/**
 * Protocol Definition for MotorControllerCanProtocol.
 * For the master.
 */
template<typename COMC>
struct MotorControllerCanProtocol: public ProtocolDef<COMC, 21, 0, 3, 0> {
  /// The object tree of the protocol
  struct ObjectTree: public Node {
		struct Settings: Node {
			struct Velocity_filter: Node {
				ValueNodeReadWriteable<TYPE_F32, 0, COMC> smoothingTf;
			} velocity_filter; 
			struct Motor_parameters: Node {
				ValueNodeReadable<TYPE_INT16, 1, COMC> encoderElectricalOffset;
				ValueNodeReadable<TYPE_UINT8, 2, COMC> electricalRotationsPerRevolution;
				ValueNodeReadableEnum<MOTOR_CONFIG_DIRECTION, 3, COMC> motorDirection;
				ValueNodeReadableEnum<BOOL, 4, COMC> motorParametersValid;
			} motor_parameters; 
		} settings; 
		struct Debug: Node {
			ValueNodeReadable<TYPE_UINT16, 5, COMC> clientRxBufferNumPackages;
			ValueNodeReadable<TYPE_UINT16, 6, COMC> clientTxBufferNumPackages;
		} debug; 
		struct Motor: Node {
			ValueNodeReadableEnum<MOTOR_OPERATION_MODE, 7, COMC> operationMode;
			ValueNodeReadWriteableEnum<MOTOR_ENABLED, 8, COMC> enabled;
			ValueNodeReadWriteable<TYPE_F32, 9, COMC> maxThrottle;
			struct Current_values: Node {
				ValueNodeReadable<TYPE_F32, 10, COMC> position;
				ValueNodeReadable<TYPE_F32, 11, COMC> velocity;
				ValueNodeReadable<TYPE_F32, 12, COMC> velocityNonFiltered;
				ValueNodeReadable<TYPE_F32, 13, COMC> torque;
			} current_values; 
			struct Target_values_pd: Node {
				ValueNodeReadWriteable<TYPE_F32, 14, COMC> position;
				ValueNodeReadWriteable<TYPE_F32, 15, COMC> velocity;
				ValueNodeReadWriteable<TYPE_F32, 16, COMC> gainP;
				ValueNodeReadWriteable<TYPE_F32, 17, COMC> gainD;
			} target_values_pd; 
			ValueNodeReadable<TYPE_F32, 18, COMC> temperature;
			struct Test_pd_mode: Node {
				ValueNodeReadWriteableEnum<BOOL, 19, COMC> active;
			} test_pd_mode; 
		} motor; 
		struct CliTool: Node {
			ValueNodeReadable<TYPE_UINT8, 20, COMC> version;
		} cliTool; 

  } objectTree;


  /// The remote calls of the protocol
  struct RemoteCalls {
		RemoteCallCaller<0, StartMotorInitSequenceArgDataCaller, StartMotorInitSequenceReturnDataCaller, VOID_ENUM, COMC> StartMotorInitSequence;
		RemoteCallCaller<1, SetMotorParametersArgDataCaller, VoidRemoteCallDataReadable, VOID_ENUM, COMC> SetMotorParameters;
		RemoteCallCaller<2, ChangeMotorOperationModeArgDataCaller, VoidRemoteCallDataReadable, REQUEST_MOTOR_OPERATION_MODE_ERROR, COMC> ChangeMotorOperationMode;

  } remoteCalls;


  /// the index is the node id belonging to the referenced node value
  OTNodeIDsTable<21> otNodeIDsTable = {
		valueNodeAsAbstract(objectTree.settings.velocity_filter.smoothingTf),
		valueNodeAsAbstract(objectTree.settings.motor_parameters.encoderElectricalOffset),
		valueNodeAsAbstract(objectTree.settings.motor_parameters.electricalRotationsPerRevolution),
		valueNodeAsAbstract(objectTree.settings.motor_parameters.motorDirection),
		valueNodeAsAbstract(objectTree.settings.motor_parameters.motorParametersValid),
		valueNodeAsAbstract(objectTree.debug.clientRxBufferNumPackages),
		valueNodeAsAbstract(objectTree.debug.clientTxBufferNumPackages),
		valueNodeAsAbstract(objectTree.motor.operationMode),
		valueNodeAsAbstract(objectTree.motor.enabled),
		valueNodeAsAbstract(objectTree.motor.maxThrottle),
		valueNodeAsAbstract(objectTree.motor.current_values.position),
		valueNodeAsAbstract(objectTree.motor.current_values.velocity),
		valueNodeAsAbstract(objectTree.motor.current_values.velocityNonFiltered),
		valueNodeAsAbstract(objectTree.motor.current_values.torque),
		valueNodeAsAbstract(objectTree.motor.target_values_pd.position),
		valueNodeAsAbstract(objectTree.motor.target_values_pd.velocity),
		valueNodeAsAbstract(objectTree.motor.target_values_pd.gainP),
		valueNodeAsAbstract(objectTree.motor.target_values_pd.gainD),
		valueNodeAsAbstract(objectTree.motor.temperature),
		valueNodeAsAbstract(objectTree.motor.test_pd_mode.active),
		valueNodeAsAbstract(objectTree.cliTool.version),

  };


  /**
   * meta data objects that are send to master on communication initialization.
   * These are generally read only.
   */
  ValueNodeAbstract *metaNodeValuesToSendOnInit[0] = {

  };


  /// Remote calls that can be called from this device
  /// the index is the call id belonging to the referenced remote call
  RemoteCallCallerAbstract *rcCallerTable[3] = {
		valueRemoteCallCallerAsAbstract(remoteCalls.StartMotorInitSequence),
		valueRemoteCallCallerAsAbstract(remoteCalls.SetMotorParameters),
		valueRemoteCallCallerAsAbstract(remoteCalls.ChangeMotorOperationMode),

  };

  /// Remote calls that are callable on this device. The caller will be another device.
  /// the index is the call id belonging to the referenced remote call
  RemoteCallCallableAbstract *rcCallableTable[0] = {

  };


  explicit MotorControllerCanProtocol(COMC *sotCanCommunication)
  : ProtocolDef<COMC, 21, 0, 3, 0>(sotCanCommunication) {
    // setup all nodevalues
		objectTree.cliTool.version.__setProtocolRef(sotCanCommunication);
		objectTree.debug.clientRxBufferNumPackages.__setProtocolRef(sotCanCommunication);
		objectTree.debug.clientTxBufferNumPackages.__setProtocolRef(sotCanCommunication);
		objectTree.motor.current_values.position.__setProtocolRef(sotCanCommunication);
		objectTree.motor.current_values.torque.__setProtocolRef(sotCanCommunication);
		objectTree.motor.current_values.velocity.__setProtocolRef(sotCanCommunication);
		objectTree.motor.current_values.velocityNonFiltered.__setProtocolRef(sotCanCommunication);
		objectTree.motor.enabled.__setProtocolRef(sotCanCommunication);
		objectTree.motor.maxThrottle.__setProtocolRef(sotCanCommunication);
		objectTree.motor.operationMode.__setProtocolRef(sotCanCommunication);
		objectTree.motor.target_values_pd.gainD.__setProtocolRef(sotCanCommunication);
		objectTree.motor.target_values_pd.gainP.__setProtocolRef(sotCanCommunication);
		objectTree.motor.target_values_pd.position.__setProtocolRef(sotCanCommunication);
		objectTree.motor.target_values_pd.velocity.__setProtocolRef(sotCanCommunication);
		objectTree.motor.temperature.__setProtocolRef(sotCanCommunication);
		objectTree.motor.test_pd_mode.active.__setProtocolRef(sotCanCommunication);
		objectTree.settings.motor_parameters.electricalRotationsPerRevolution.__setProtocolRef(sotCanCommunication);
		objectTree.settings.motor_parameters.encoderElectricalOffset.__setProtocolRef(sotCanCommunication);
		objectTree.settings.motor_parameters.motorDirection.__setProtocolRef(sotCanCommunication);
		objectTree.settings.motor_parameters.motorParametersValid.__setProtocolRef(sotCanCommunication);
		objectTree.settings.velocity_filter.smoothingTf.__setProtocolRef(sotCanCommunication);
		remoteCalls.ChangeMotorOperationMode.__setProtocolRef(sotCanCommunication);
		remoteCalls.SetMotorParameters.__setProtocolRef(sotCanCommunication);
		remoteCalls.StartMotorInitSequence.__setProtocolRef(sotCanCommunication);

  };
};


}
